services:
  prices_lib:
    build:
      dockerfile: Dockerfile
      context: .docker/php
    container_name: prices_lib
    restart: no
    working_dir: /app
    volumes:
      - ./:/app

  prices_composer:
    build:
      dockerfile: Dockerfile
      context: .docker/composer
    container_name: prices_composer
    restart: no
    working_dir: /app
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: shared
